[package]
name = "betaflight-app"
version = "2025.12.0"
description = "Betaflight App"
authors = ["Betaflight Team"]
license = "GPL-3.0"
repository = "https://github.com/betaflight/betaflight-configurator"
edition = "2024"

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "betaflight_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5", features = [] }

[dependencies]
tauri = { version = "2.9", features = [] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri-plugin-opener = "2.5.2"
tauri-plugin-serialplugin = "2.21.1"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
