name: 'Deployment (PR and Push to master/maintenance)'
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - master
      - '*-maintenance'
  push:
    branches:
      - master
      - '*-maintenance'

jobs:
  # Job 1: Build the code (no secrets here)
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      debug_build: ${{ github.event_name == 'pull_request_target' || github.event_name == 'pull_request' }}
      commit_ref: ${{ github.event_name == 'pull_request_target' || github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
    secrets:
      RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
      RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
      RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
      RELEASE_KEY_ALIAS_PASSWORD: ${{ secrets.RELEASE_KEY_ALIAS_PASSWORD }}

  # Deploy with secrets (no PR code checkout)
  deploy:
    name: Deploy
    needs: build
    permissions:
      actions: read
      contents: read
      deployments: write
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v5
        with:
          name: dist-files
          path: src/dist

      - name: Set alias branch name for Cloudflare
        id: branch_name
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            BRANCH=${{ github.ref_name }}
          else
            BRANCH=PR${{ github.event.pull_request.number }}
          fi
          echo "BRANCH=$BRANCH" >> $GITHUB_OUTPUT

          # Set a simple output to confirm the value
          echo "EVENT: ${{ github.event_name }}, BRANCH: $BRANCH"

      - name: Deploy to Cloudflare
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy src/dist --project-name=${{ vars.CLOUDFLARE_PROJECT_NAME }} --branch=${{ steps.branch_name.outputs.BRANCH }} --commit-dirty=true

      - name: Add deployment comment
        if: github.event_name == 'pull_request_target' || github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            üéâ Do you want to test this code? üéâ

            - üåê **[Progressive Web Application (PWA)](${{ steps.deploy.outputs.pages-deployment-alias-url }})**
            - ü§ñ **[Android APK](${{ needs.build.outputs.apk_url }})**

            ‚ö†Ô∏è **CAUTION**: The build may be unstable and result in corrupted configurations or data loss. Use only for testing! ‚ö†Ô∏è
          comment-tag: 'deployment-comment'
          mode: recreate
