name: Hide artifact links comments

on:
  pull_request_target:
    types: [synchronize, reopened]

jobs:
  hide-artifacts-link-comments:
    name: Hide artifact links
    runs-on: ubuntu-latest
    steps:
      - name: Hide comments
        uses: int128/hide-comment-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          starts-with: "Preview URL:"
